app/routes.php
<?php

Route::group(array('namespace' => 'Admin', 'prefix' => 'admin'), function() {
	Route::group(array('before' => 'auth'), function() {

	});
	Route::get('/', array('uses'					=> 'DashboardController@index', 	'as' => 'admin.index'));

	Route::resource('competencies', 				'CompetenciesController');
	Route::resource('components', 					'ComponentsController');
	Route::resource('attachments', 					'AttachmentsController');
	Route::resource('projects', 					'ProjectsController');
	Route::resource('users', 						'UsersController');
});

Route::group(array('namespace' => 'Guest'), function() {
	Route::get('/', array('uses'					=> 'HomeController@index', 			'as' => 'guest.index'));
	Route::resource('competencies', 				'CompetenciesController');
	Route::resource('components', 					'ComponentsController');
	Route::resource('projects', 					'ProjectsController');
});


Route::resource('attachments', 'AttachmentsController');

app/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Stageverslag</title>
	<link rel="stylesheet" href="/css/style.admin.css">
</head>
<body>
	<header class="container">
		<div class="wrapper">
			<nav>
				<ul>
					<li><a href="{{ URL::route('admin.index') }}">Dashboard</a></li>
					<li><a href="{{ URL::route('admin.competencies.index') }}">Competenties</a></li>
					<li><a href="{{ URL::route('admin.components.index') }}">Competentie onderdelen</a></li>
					<li><a href="{{ URL::route('admin.attachments.index') }}">Bijlages</a></li>
					<li><a href="{{ URL::route('admin.projects.index') }}">Projecten</a></li>
					<li><a href="{{ URL::route('admin.users.index') }}">Gebruikers</a></li>
				</ul>
			</nav>
		</div>
	</header>

	<div class="container">
		<div class="wrapper">
			@yield('main')
		</div>
	</div>

	<footer class="container">
		<div class="wrapper">

		</div>
	</footer>

	<script type="text/javascript" src="/vendor/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="/js/app.admin.js"></script>
</body>
</html>